# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.6.0_1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.6.0_1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/cassini/work/embedded/lcdmaster

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/cassini/work/embedded/lcdmaster

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.6.0_1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.6.0_1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cassini/work/embedded/lcdmaster/CMakeFiles /Users/cassini/work/embedded/lcdmaster/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/cassini/work/embedded/lcdmaster/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named arduino-lcd

# Build rule for target.
arduino-lcd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 arduino-lcd
.PHONY : arduino-lcd

# fast build rule for target.
arduino-lcd/fast:
	$(MAKE) -f CMakeFiles/arduino-lcd.dir/build.make CMakeFiles/arduino-lcd.dir/build
.PHONY : arduino-lcd/fast

#=============================================================================
# Target rules for targets named PLATFORMIO_REBUILD_PROJECT_INDEX

# Build rule for target.
PLATFORMIO_REBUILD_PROJECT_INDEX: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PLATFORMIO_REBUILD_PROJECT_INDEX
.PHONY : PLATFORMIO_REBUILD_PROJECT_INDEX

# fast build rule for target.
PLATFORMIO_REBUILD_PROJECT_INDEX/fast:
	$(MAKE) -f CMakeFiles/PLATFORMIO_REBUILD_PROJECT_INDEX.dir/build.make CMakeFiles/PLATFORMIO_REBUILD_PROJECT_INDEX.dir/build
.PHONY : PLATFORMIO_REBUILD_PROJECT_INDEX/fast

#=============================================================================
# Target rules for targets named PLATFORMIO_BUILD

# Build rule for target.
PLATFORMIO_BUILD: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PLATFORMIO_BUILD
.PHONY : PLATFORMIO_BUILD

# fast build rule for target.
PLATFORMIO_BUILD/fast:
	$(MAKE) -f CMakeFiles/PLATFORMIO_BUILD.dir/build.make CMakeFiles/PLATFORMIO_BUILD.dir/build
.PHONY : PLATFORMIO_BUILD/fast

#=============================================================================
# Target rules for targets named PLATFORMIO_PROGRAM

# Build rule for target.
PLATFORMIO_PROGRAM: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PLATFORMIO_PROGRAM
.PHONY : PLATFORMIO_PROGRAM

# fast build rule for target.
PLATFORMIO_PROGRAM/fast:
	$(MAKE) -f CMakeFiles/PLATFORMIO_PROGRAM.dir/build.make CMakeFiles/PLATFORMIO_PROGRAM.dir/build
.PHONY : PLATFORMIO_PROGRAM/fast

#=============================================================================
# Target rules for targets named PLATFORMIO_CLEAN

# Build rule for target.
PLATFORMIO_CLEAN: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PLATFORMIO_CLEAN
.PHONY : PLATFORMIO_CLEAN

# fast build rule for target.
PLATFORMIO_CLEAN/fast:
	$(MAKE) -f CMakeFiles/PLATFORMIO_CLEAN.dir/build.make CMakeFiles/PLATFORMIO_CLEAN.dir/build
.PHONY : PLATFORMIO_CLEAN/fast

#=============================================================================
# Target rules for targets named PLATFORMIO_UPLOAD

# Build rule for target.
PLATFORMIO_UPLOAD: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PLATFORMIO_UPLOAD
.PHONY : PLATFORMIO_UPLOAD

# fast build rule for target.
PLATFORMIO_UPLOAD/fast:
	$(MAKE) -f CMakeFiles/PLATFORMIO_UPLOAD.dir/build.make CMakeFiles/PLATFORMIO_UPLOAD.dir/build
.PHONY : PLATFORMIO_UPLOAD/fast

#=============================================================================
# Target rules for targets named PLATFORMIO_UPDATE_ALL

# Build rule for target.
PLATFORMIO_UPDATE_ALL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PLATFORMIO_UPDATE_ALL
.PHONY : PLATFORMIO_UPDATE_ALL

# fast build rule for target.
PLATFORMIO_UPDATE_ALL/fast:
	$(MAKE) -f CMakeFiles/PLATFORMIO_UPDATE_ALL.dir/build.make CMakeFiles/PLATFORMIO_UPDATE_ALL.dir/build
.PHONY : PLATFORMIO_UPDATE_ALL/fast

#=============================================================================
# Target rules for targets named PLATFORMIO_UPLOADFS

# Build rule for target.
PLATFORMIO_UPLOADFS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PLATFORMIO_UPLOADFS
.PHONY : PLATFORMIO_UPLOADFS

# fast build rule for target.
PLATFORMIO_UPLOADFS/fast:
	$(MAKE) -f CMakeFiles/PLATFORMIO_UPLOADFS.dir/build.make CMakeFiles/PLATFORMIO_UPLOADFS.dir/build
.PHONY : PLATFORMIO_UPLOADFS/fast

Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_okmsg.o: Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_okmsg.cpp.o

.PHONY : Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_okmsg.o

# target to build an object file
Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_okmsg.cpp.o:
	$(MAKE) -f CMakeFiles/arduino-lcd.dir/build.make CMakeFiles/arduino-lcd.dir/Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_okmsg.cpp.o
.PHONY : Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_okmsg.cpp.o

Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_okmsg.i: Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_okmsg.cpp.i

.PHONY : Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_okmsg.i

# target to preprocess a source file
Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_okmsg.cpp.i:
	$(MAKE) -f CMakeFiles/arduino-lcd.dir/build.make CMakeFiles/arduino-lcd.dir/Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_okmsg.cpp.i
.PHONY : Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_okmsg.cpp.i

Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_okmsg.s: Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_okmsg.cpp.s

.PHONY : Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_okmsg.s

# target to generate assembly for a file
Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_okmsg.cpp.s:
	$(MAKE) -f CMakeFiles/arduino-lcd.dir/build.make CMakeFiles/arduino-lcd.dir/Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_okmsg.cpp.s
.PHONY : Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_okmsg.cpp.s

Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_select5.o: Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_select5.cpp.o

.PHONY : Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_select5.o

# target to build an object file
Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_select5.cpp.o:
	$(MAKE) -f CMakeFiles/arduino-lcd.dir/build.make CMakeFiles/arduino-lcd.dir/Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_select5.cpp.o
.PHONY : Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_select5.cpp.o

Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_select5.i: Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_select5.cpp.i

.PHONY : Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_select5.i

# target to preprocess a source file
Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_select5.cpp.i:
	$(MAKE) -f CMakeFiles/arduino-lcd.dir/build.make CMakeFiles/arduino-lcd.dir/Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_select5.cpp.i
.PHONY : Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_select5.cpp.i

Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_select5.s: Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_select5.cpp.s

.PHONY : Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_select5.s

# target to generate assembly for a file
Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_select5.cpp.s:
	$(MAKE) -f CMakeFiles/arduino-lcd.dir/build.make CMakeFiles/arduino-lcd.dir/Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_select5.cpp.s
.PHONY : Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_select5.cpp.s

Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_slider16.o: Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_slider16.cpp.o

.PHONY : Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_slider16.o

# target to build an object file
Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_slider16.cpp.o:
	$(MAKE) -f CMakeFiles/arduino-lcd.dir/build.make CMakeFiles/arduino-lcd.dir/Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_slider16.cpp.o
.PHONY : Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_slider16.cpp.o

Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_slider16.i: Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_slider16.cpp.i

.PHONY : Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_slider16.i

# target to preprocess a source file
Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_slider16.cpp.i:
	$(MAKE) -f CMakeFiles/arduino-lcd.dir/build.make CMakeFiles/arduino-lcd.dir/Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_slider16.cpp.i
.PHONY : Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_slider16.cpp.i

Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_slider16.s: Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_slider16.cpp.s

.PHONY : Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_slider16.s

# target to generate assembly for a file
Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_slider16.cpp.s:
	$(MAKE) -f CMakeFiles/arduino-lcd.dir/build.make CMakeFiles/arduino-lcd.dir/Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_slider16.cpp.s
.PHONY : Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_slider16.cpp.s

Users/cassini/work/embedded/arduino-lcd/src/main.o: Users/cassini/work/embedded/arduino-lcd/src/main.cpp.o

.PHONY : Users/cassini/work/embedded/arduino-lcd/src/main.o

# target to build an object file
Users/cassini/work/embedded/arduino-lcd/src/main.cpp.o:
	$(MAKE) -f CMakeFiles/arduino-lcd.dir/build.make CMakeFiles/arduino-lcd.dir/Users/cassini/work/embedded/arduino-lcd/src/main.cpp.o
.PHONY : Users/cassini/work/embedded/arduino-lcd/src/main.cpp.o

Users/cassini/work/embedded/arduino-lcd/src/main.i: Users/cassini/work/embedded/arduino-lcd/src/main.cpp.i

.PHONY : Users/cassini/work/embedded/arduino-lcd/src/main.i

# target to preprocess a source file
Users/cassini/work/embedded/arduino-lcd/src/main.cpp.i:
	$(MAKE) -f CMakeFiles/arduino-lcd.dir/build.make CMakeFiles/arduino-lcd.dir/Users/cassini/work/embedded/arduino-lcd/src/main.cpp.i
.PHONY : Users/cassini/work/embedded/arduino-lcd/src/main.cpp.i

Users/cassini/work/embedded/arduino-lcd/src/main.s: Users/cassini/work/embedded/arduino-lcd/src/main.cpp.s

.PHONY : Users/cassini/work/embedded/arduino-lcd/src/main.s

# target to generate assembly for a file
Users/cassini/work/embedded/arduino-lcd/src/main.cpp.s:
	$(MAKE) -f CMakeFiles/arduino-lcd.dir/build.make CMakeFiles/arduino-lcd.dir/Users/cassini/work/embedded/arduino-lcd/src/main.cpp.s
.PHONY : Users/cassini/work/embedded/arduino-lcd/src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... arduino-lcd"
	@echo "... PLATFORMIO_REBUILD_PROJECT_INDEX"
	@echo "... PLATFORMIO_BUILD"
	@echo "... PLATFORMIO_PROGRAM"
	@echo "... edit_cache"
	@echo "... PLATFORMIO_CLEAN"
	@echo "... PLATFORMIO_UPLOAD"
	@echo "... PLATFORMIO_UPDATE_ALL"
	@echo "... PLATFORMIO_UPLOADFS"
	@echo "... Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_okmsg.o"
	@echo "... Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_okmsg.i"
	@echo "... Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_okmsg.s"
	@echo "... Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_select5.o"
	@echo "... Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_select5.i"
	@echo "... Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_select5.s"
	@echo "... Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_slider16.o"
	@echo "... Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_slider16.i"
	@echo "... Users/cassini/work/embedded/arduino-lcd/src/lcdconfig_slider16.s"
	@echo "... Users/cassini/work/embedded/arduino-lcd/src/main.o"
	@echo "... Users/cassini/work/embedded/arduino-lcd/src/main.i"
	@echo "... Users/cassini/work/embedded/arduino-lcd/src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

