//
// Created by c018 on 17.11.16.
//

#ifndef ARDUINO_LCD_LCDCONFIG_COMMON_H
#define ARDUINO_LCD_LCDCONFIG_COMMON_H

#define LCDCONFIG_STATE_NEW             0
#define LCDCONFIG_STATE_INPROGRESS      1
#define LCDCONFIG_STATE_SELECTED        2
#define LCDCONFIG_STATE_UP              3


#endif //ARDUINO_LCD_LCDCONFIG_COMMON_H
